sudo: required

language: groovy

jdk:
   - openjdk7
   - oraclejdk7
   - oraclejdk8

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - gradle dockerBuildImage bintrayUpload


notifications:
  email:
    recipients:
      - me@eike-hirsch.net
