language: groovy

jdk:
   - openjdk7
   - oraclejdk7
   - oraclejdk8

notifications:
  email:
    recipients:
      - me@eike-hirsch.net

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - gradle bintrayUpload
