sudo: required

language: groovy

jdk:
   - openjdk7
   - oraclejdk7
   - oraclejdk8

addons:
   # Fix OpenJDK builds
   # https://github.com/travis-ci/travis-ci/issues/5227
   hostname: localhost

services:
  - docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - gradle dockerBuildImage bintrayUpload


notifications:
  email:
    recipients:
      - me@eike-hirsch.net
